'use strict';
const paths = {
 home:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 about:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 assignments:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/><path d="M3 9h18"/>',
 markets:'<path d="M3 3v18h18M6 15l5-5 4 3 6-8"/><path d="M17 5h4v4"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18M8 15h2m4 0h2"/>',
 plus:'<path d="M12 5v14M5 12h14"/>', close:'<path d="m6 6 12 12M6 18 18 6"/>', left:'<path d="m15 6-6 6 6 6"/>', right:'<path d="m9 6 6 6-6 6"/>', menu:'<path d="M4 6h16M4 12h16M4 18h16"/>', check:'<path d="m5 12 4 4L19 6"/>', edit:'<path d="m16 3 5 5-12 12H4v-5ZM13 6l5 5"/>', trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>', globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a18 18 0 0 1 0 18 18 18 0 0 1 0-18"/>'
};
const icon=(name,size=20)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.home}</svg>`;
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page=document.body.dataset.page;
const navItems=[['home','/','首页'],['assignments','/assignments/','作业仓库'],['about','/about/','个人简介'],['markets','/markets/','金融市场'],['calendar','/calendar/','个人日历']];
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon,25));
document.querySelector('#shell').innerHTML=`<header class="mobile-bar"><a class="mobile-brand" href="/"><span class="brand-mark">W.</span>Windysunny</a><button type="button" class="menu-button" aria-label="打开导航" aria-controls="sidebar" aria-expanded="false">${icon('menu')}</button></header><aside class="sidebar" id="sidebar"><a href="/" class="brand"><span class="brand-mark">W.</span><span><span class="brand-name">Windysunny</span><br><span class="brand-caption">PERSONAL SPACE</span></span></a><p class="nav-label">我的空间 / SPACE</p><nav class="nav" aria-label="主导航">${navItems.map(([id,url,label])=>`<a href="${url}" ${id===page?'class="active" aria-current="page"':''}>${icon(id)}${label}</a>`).join('')}</nav><div class="sidebar-bottom"><a class="person" href="/about/"><span class="avatar">JZ</span><span><strong>金正煊</strong><small>@Windysunny</small></span></a><p class="sidebar-note">一处空间，安放好奇与日常。</p></div></aside>`;
document.querySelector('.menu-button').addEventListener('click',event=>{const button=event.currentTarget;const open=document.querySelector('#sidebar').classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'关闭导航':'打开导航');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('#sidebar').classList.remove('open');document.querySelector('.menu-button').setAttribute('aria-expanded','false');}});
let today=new Date();const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
let todayKey=dateKey(today);const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d);};
function renderTodayLabel(){document.querySelectorAll('[data-today]').forEach(el=>el.innerHTML=icon('calendar',16)+escapeHtml(today.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})));}
renderTodayLabel();
let toastTimer;function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3800);}
const STORAGE_KEY='windysunny-calendar-v1';
let events=[],storageIssue='';
function loadEvents(){try{const raw=localStorage.getItem(STORAGE_KEY);const parsed=raw?JSON.parse(raw):[];if(!Array.isArray(parsed))throw Error('format');events=parsed.filter(e=>e&&typeof e.id==='string'&&typeof e.title==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(e.date));}catch{storageIssue='当前浏览器无法读取日历记录。请检查是否禁用了网站存储，或换用普通浏览窗口。';events=[];}}
loadEvents();
if(storageIssue){const el=document.createElement('p');el.className='storage-error';el.textContent=storageIssue;document.querySelector('.page-head').after(el);}
function miniCalendar(){const container=document.querySelector('#mini-calendar');if(!container)return;document.querySelector('#mini-title').textContent=`${today.getFullYear()} 年 ${today.getMonth()+1} 月`;const first=new Date(today.getFullYear(),today.getMonth(),1);const shift=(first.getDay()+6)%7;const count=Math.ceil((shift+new Date(today.getFullYear(),today.getMonth()+1,0).getDate())/7)*7;let html=['一','二','三','四','五','六','日'].map(x=>`<span class="week">${x}</span>`).join('');for(let i=0;i<count;i++){const d=new Date(today.getFullYear(),today.getMonth(),1-shift+i),key=dateKey(d);html+=`<a class="mini-day ${d.getMonth()!==today.getMonth()?'outside':''} ${key===todayKey?'today':''} ${events.some(e=>e.date===key)?'has-event':''}" href="/calendar/?date=${key}" aria-label="${key}${key===todayKey?' 今天':''}">${d.getDate()}</a>`;}container.innerHTML=`<div class="mini-grid">${html}</div>`;}
function renderHomeAgenda(){const el=document.querySelector('#upcoming-home');if(!el)return;const upcoming=events.filter(e=>e.date>=todayKey).sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||'')).slice(0,3);el.innerHTML=upcoming.length?upcoming.map(e=>{const d=parseDate(e.date);return `<a href="/calendar/?date=${e.date}" class="event-row"><span class="event-date-block">${d.getMonth()+1}月<strong>${d.getDate()}</strong></span><span><h3>${escapeHtml(e.title)}</h3><p>${e.time?escapeHtml(e.time):'全天'} · ${escapeHtml(e.category||'个人')}</p></span></a>`;}).join(''):`<div class="empty-agenda"><div class="empty-icon">${icon('calendar',23)}</div><h3>好日子，值得记下来</h3><p>还没有待办日期。给生日、考试或重要约定留一个位置。</p></div>`;}
miniCalendar();renderHomeAgenda();
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){loadEvents();miniCalendar();renderHomeAgenda();if(typeof renderCalendar==='function')renderCalendar();}});
function refreshToday(){const current=new Date();if(dateKey(current)===todayKey)return;const previous=todayKey;today=current;todayKey=dateKey(current);renderTodayLabel();miniCalendar();renderHomeAgenda();window.dispatchEvent(new CustomEvent('calendar-date-changed',{detail:{previous}}));}
window.addEventListener('focus',refreshToday);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshToday();});setInterval(refreshToday,60000);
