'use strict';
// This public manifest is deployed with the site; every visitor sees the same coursework.
// Entry: {title, course, date: 'YYYY-MM-DD', description?, url, type?: '报告'|'文档'|'代码'|'演示'|'网页'}
const assignmentList=document.querySelector('#assignment-list');
const courseFilter=document.querySelector('#course-filter');
let assignments=[];
function safeAssignmentURL(value){if(typeof value!=='string'||!value.trim())throw Error('缺少作业链接');const url=new URL(value,location.origin);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('作业链接无效');return url.href;}
function normalizeAssignment(item){if(!item||typeof item!=='object'||typeof item.title!=='string'||!item.title.trim()||typeof item.course!=='string'||!item.course.trim()||typeof item.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(item.date)||dateKey(parseDate(item.date))!==item.date)throw Error('作业清单格式有误');return {title:item.title.trim(),course:item.course.trim(),date:item.date,description:typeof item.description==='string'?item.description:'',type:typeof item.type==='string'?item.type:'作业',url:safeAssignmentURL(item.url)};}
function renderAssignments(){const visible=assignments.filter(item=>!courseFilter.value||item.course===courseFilter.value);document.querySelector('#assignment-count').textContent=`${visible.length} 份作业`;assignmentList.setAttribute('aria-busy','false');if(!assignments.length){assignmentList.innerHTML=`<div class="archive-empty"><span class="archive-empty-icon" aria-hidden="true">${icon('assignments',32)}</span><h3>第一份作业，准备中</h3><p>目前还没有公开的作业。<br>发布后，你可以在这里查看课程、日期和作业内容。</p><span class="empty-caption">金正煊的课程作业，将从这里开始积累。</span></div>`;return;}assignmentList.innerHTML=`<div class="assignment-rows">${visible.map(item=>`<article class="assignment-row"><div class="assignment-file-icon" aria-hidden="true">${icon('assignments',22)}</div><div class="assignment-body"><div class="assignment-meta"><span>${escapeHtml(item.course)}</span><time datetime="${item.date}">${item.date.replaceAll('-','.')} 发布</time></div><h3><a href="${escapeHtml(item.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(item.title)}</a></h3>${item.description?`<p>${escapeHtml(item.description)}</p>`:''}</div><div class="assignment-open"><span class="assignment-type">${escapeHtml(item.type)}</span><a class="text-link" href="${escapeHtml(item.url)}" target="_blank" rel="noopener noreferrer" aria-label="查看作业：${escapeHtml(item.title)}">查看作业 <span aria-hidden="true">↗</span></a></div></article>`).join('')}</div>`;}
async function loadAssignments(){assignmentList.setAttribute('aria-busy','true');assignmentList.innerHTML='<p class="archive-loading">正在读取作业…</p>';document.querySelector('#archive-controls').hidden=true;document.querySelector('#assignment-count').textContent='';try{const response=await fetch('/assignments/data.json',{cache:'no-cache'});if(!response.ok)throw Error('读取失败');const data=await response.json();if(!Array.isArray(data))throw Error('格式有误');assignments=data.map(normalizeAssignment).sort((a,b)=>b.date.localeCompare(a.date)||a.title.localeCompare(b.title,'zh-CN'));const courses=[...new Set(assignments.map(item=>item.course))].sort((a,b)=>a.localeCompare(b,'zh-CN'));courseFilter.innerHTML='<option value="">全部课程</option>'+courses.map(course=>`<option value="${escapeHtml(course)}">${escapeHtml(course)}</option>`).join('');document.querySelector('#archive-controls').hidden=courses.length<2;renderAssignments();}catch{assignmentList.setAttribute('aria-busy','false');assignmentList.innerHTML='<div class="archive-empty"><h3>作业清单暂时无法读取</h3><p>请检查网络连接，再试一次。</p><button type="button" class="button secondary" id="retry-assignments">重新加载</button></div>';document.querySelector('#retry-assignments').addEventListener('click',loadAssignments);}}
courseFilter.addEventListener('change',renderAssignments);
document.querySelector('#copy-repository').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('https://windysunny-space.vercel.app/assignments/');toast('作业仓库链接已复制，可以发给老师了');}catch{toast('暂时无法自动复制，请复制浏览器地址栏中的网址。');}});
loadAssignments();
