'use strict';
const categories=['个人','生日','学习','约定','纪念日'];
const categoryClass=value=>`category-${Math.max(0,categories.indexOf(value))}`;
function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=parseDate(value);return d.getFullYear()>=1900&&d.getFullYear()<=2100&&dateKey(d)===value;}
let initialDate=new URLSearchParams(location.search).get('date');
let selected=validDate(initialDate)?initialDate:todayKey;
let viewYear=parseDate(selected).getFullYear(),viewMonth=parseDate(selected).getMonth();
const grid=document.querySelector('#calendar-grid'),eventDialog=document.querySelector('#event-dialog'),eventForm=document.querySelector('#event-form'),deleteDialog=document.querySelector('#delete-dialog');
let deleteId=null;
const yearSelect=document.querySelector('#year-select'),monthSelect=document.querySelector('#month-select');
yearSelect.innerHTML=Array.from({length:201},(_,i)=>`<option value="${1900+i}">${1900+i} 年</option>`).join('');
monthSelect.innerHTML=Array.from({length:12},(_,i)=>`<option value="${i}">${i+1} 月</option>`).join('');
function sortedRecords(records){return [...records].sort((a,b)=>a.date.localeCompare(b.date)||(a.time||'').localeCompare(b.time||'')||a.title.localeCompare(b.title,'zh-CN'));}
function eventDetails(e,compact=false){return `<div class="event-detail ${categoryClass(e.category)}"><div class="event-detail-top"><span class="category-tag ${categoryClass(e.category)}">${escapeHtml(e.category)}</span><span class="small-label">${e.time?escapeHtml(e.time):'全天'}</span></div><h3>${escapeHtml(e.title)}</h3>${e.note?`<p class="event-note">${escapeHtml(e.note)}</p>`:''}<div class="event-actions"><button type="button" data-edit="${escapeHtml(e.id)}" aria-label="编辑：${escapeHtml(e.title)}">${icon('edit',15)}编辑</button><button type="button" data-delete="${escapeHtml(e.id)}" aria-label="删除：${escapeHtml(e.title)}">${icon('trash',15)}删除</button></div></div>`;}
function renderCalendar(){
 yearSelect.value=String(viewYear);monthSelect.value=String(viewMonth);
 document.querySelector('#prev-month').disabled=viewYear===1900&&viewMonth===0;document.querySelector('#next-month').disabled=viewYear===2100&&viewMonth===11;
 const first=new Date(viewYear,viewMonth,1),start=(first.getDay()+6)%7;let html='';
 for(let i=0;i<42;i++){const day=new Date(viewYear,viewMonth,1-start+i),key=dateKey(day),dayEvents=sortedRecords(events.filter(e=>e.date===key)),outside=day.getMonth()!==viewMonth;const label=`${day.getFullYear()}年${day.getMonth()+1}月${day.getDate()}日${key===todayKey?'，今天':''}，${dayEvents.length}条记录`;
 html+=`<button type="button" class="calendar-day ${outside?'outside':''} ${key===todayKey?'is-today':''} ${key===selected?'selected':''}" data-date="${key}" aria-label="${label}" aria-pressed="${key===selected}" ${validDate(key)?'':'disabled'}><span class="day-number">${day.getDate()}</span><span class="cell-events">${dayEvents.slice(0,2).map(e=>`<span class="cell-event ${categoryClass(e.category)}">${escapeHtml(e.title)}</span>`).join('')}${dayEvents.length>2?`<span class="more-events">+${dayEvents.length-2} 条</span>`:''}</span>${dayEvents.length?'<span class="mobile-event-dot" aria-hidden="true"></span>':''}</button>`;}
 grid.innerHTML=html;
 const day=parseDate(selected);document.querySelector('#selected-heading').textContent=`${day.getMonth()+1} 月 ${day.getDate()} 日`;document.querySelector('#selected-weekday').textContent=`${day.getFullYear()} 年 · ${day.toLocaleDateString('zh-CN',{weekday:'long'})}${selected===todayKey?' · 今天':''}`;
 const records=sortedRecords(events.filter(e=>e.date===selected));document.querySelector('#day-events').innerHTML=records.length?records.map(e=>eventDetails(e)).join(''):`<div class="day-empty"><span class="empty-icon">${icon('calendar',24)}</span><h3>这一天，还留着空白</h3><p>为重要的事，留下一笔。</p></div>`;
 const monthKey=`${viewYear}-${String(viewMonth+1).padStart(2,'0')}`;const monthly=sortedRecords(events.filter(e=>e.date.startsWith(monthKey)));document.querySelector('#month-count').textContent=`${viewMonth+1} 月 · ${monthly.length} 条记录`;
 document.querySelector('#month-events').innerHTML=monthly.length?monthly.map(e=>`<button type="button" class="month-event-row" data-select="${e.date}"><span class="event-date-block">${viewMonth+1}月<strong>${parseDate(e.date).getDate()}</strong></span><span class="month-event-title"><strong>${escapeHtml(e.title)}</strong><small>${e.time?escapeHtml(e.time):'全天'} · ${parseDate(e.date).toLocaleDateString('zh-CN',{weekday:'long'})}</small></span><span class="category-tag ${categoryClass(e.category)}">${escapeHtml(e.category)}</span><span class="row-arrow" aria-hidden="true">→</span></button>`).join(''):`<div class="month-empty">这个月还没有重要日期。点击右上角“添加重要日期”，记下第一件事。</div>`;
}
function selectDate(key){if(!validDate(key))return;selected=key;viewYear=parseDate(key).getFullYear();viewMonth=parseDate(key).getMonth();renderCalendar();}
function showForm(record=null,prefill={}){eventForm.reset();eventForm.elements.id.value=record?.id||'';eventForm.elements.title.value=record?.title||prefill.title||'';eventForm.elements.date.value=record?.date||prefill.date||selected;eventForm.elements.time.value=record?.time||'';eventForm.elements.category.value=record?.category||'个人';eventForm.elements.note.value=record?.note||'';document.querySelector('#dialog-title').textContent=record?'编辑重要日期':'添加重要日期';document.querySelector('#form-error').textContent='';eventDialog.showModal();eventForm.elements.title.focus();}
function saveRecords(next){if(storageIssue)throw new Error(storageIssue);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));events=next;}catch{throw new Error('未能保存：浏览器存储不可用或空间不足。请保留填写内容，检查浏览器设置后重试。');}}
function validateRecord(value){const title=String(value.title||'').trim();if(!title||title.length>80)throw Error('请输入 1—80 个字的事项名称。');if(!validDate(value.date))throw Error('请选择 1900—2100 年之间的有效日期。');if(value.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(value.time))throw Error('请输入有效的时间。');if(!categories.includes(value.category))throw Error('请选择有效分类。');const note=String(value.note||'').trim();if(note.length>500)throw Error('备注不能超过 500 个字。');return {title,date:value.date,time:value.time||'',category:value.category,note};}
eventForm.addEventListener('submit',e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(eventForm));const validated=validateRecord(data);const isEdit=Boolean(data.id);if(isEdit&&!events.some(e=>e.id===data.id))throw Error('这条记录已被删除，请关闭窗口后重试。');const record={...validated,id:data.id||crypto.randomUUID()};const next=isEdit?events.map(e=>e.id===record.id?record:e):[...events,record];saveRecords(next);selectDate(record.date);eventDialog.close();toast(isEdit?'日期已更新':'重要日期已保存');}catch(err){document.querySelector('#form-error').textContent=err.message;}});
document.querySelectorAll('.close-dialog').forEach(button=>button.addEventListener('click',()=>eventDialog.close()));
document.querySelectorAll('.close-delete').forEach(button=>button.addEventListener('click',()=>deleteDialog.close()));
document.querySelector('#new-event').addEventListener('click',()=>showForm());document.querySelector('#add-day').addEventListener('click',()=>showForm());
document.querySelector('#prev-month').addEventListener('click',()=>changeMonth(-1));document.querySelector('#next-month').addEventListener('click',()=>changeMonth(1));
function changeMonth(delta){const d=new Date(viewYear,viewMonth+delta,1);if(d.getFullYear()<1900||d.getFullYear()>2100)return;viewYear=d.getFullYear();viewMonth=d.getMonth();selected=dateKey(d);renderCalendar();}
yearSelect.addEventListener('change',()=>{viewYear=Number(yearSelect.value);selected=dateKey(new Date(viewYear,viewMonth,1));renderCalendar();});monthSelect.addEventListener('change',()=>{viewMonth=Number(monthSelect.value);selected=dateKey(new Date(viewYear,viewMonth,1));renderCalendar();});document.querySelector('#go-today').addEventListener('click',()=>{refreshToday();selectDate(todayKey);});
grid.addEventListener('click',e=>{const button=e.target.closest('[data-date]');if(button)selectDate(button.dataset.date);});
grid.addEventListener('keydown',e=>{const button=e.target.closest('[data-date]');if(!button)return;const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[e.key];if(delta){e.preventDefault();const d=parseDate(button.dataset.date);d.setDate(d.getDate()+delta);const key=dateKey(d);selectDate(key);grid.querySelector(`[data-date="${key}"]`)?.focus();}});
document.querySelector('#month-events').addEventListener('click',e=>{const button=e.target.closest('[data-select]');if(button){selectDate(button.dataset.select);document.querySelector('.day-panel').scrollIntoView({behavior:'smooth',block:'nearest'});}});
document.querySelector('#day-events').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const record=events.find(x=>x.id===edit.dataset.edit);if(record)showForm(record);}if(del){const record=events.find(x=>x.id===del.dataset.delete);if(!record)return;deleteId=record.id;document.querySelector('#delete-description').textContent=record.title;document.querySelector('#delete-error').textContent='';deleteDialog.showModal();}});
document.querySelector('#confirm-delete').addEventListener('click',()=>{try{saveRecords(events.filter(e=>e.id!==deleteId));renderCalendar();deleteDialog.close();toast('记录已删除');}catch(err){document.querySelector('#delete-error').textContent=err.message;}});
renderCalendar();
window.addEventListener('calendar-date-changed',e=>{if(selected===e.detail.previous&&!eventDialog.open){selectDate(todayKey);}else{renderCalendar();}});
// Progressive enhancement: agents may open the same form; saving remains a visible user action.
if(document.modelContext?.registerTool){const controller=new AbortController();const tool={name:'start_calendar_event_creation',title:'填写重要日期',description:'打开个人日历的添加表单并填写名称和日期；不会保存，用户点击保存后才创建记录。',inputSchema:{type:'object',properties:{date:{type:'string',description:'YYYY-MM-DD，1900至2100年'},title:{type:'string',maxLength:80}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!validDate(input.date)||typeof input.title!=='undefined'&&typeof input.title!=='string'||(input.title||'').length>80)throw Error('日期或名称无效');if(eventDialog.open)throw Error('已有编辑表单打开，请先完成或关闭');selectDate(input.date);showForm(null,{date:input.date,title:input.title||''});return {status:'form_opened',saved:false,date:input.date};}};try{Promise.resolve(document.modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{});window.addEventListener('pagehide',()=>controller.abort(),{once:true});}catch{}}
